# Generated by Django 5.1.6 on 2025-03-30 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0002_student_delete_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Roll_Number', models.CharField(max_length=750)),
                ('Candidate_Name', models.CharField(max_length=755)),
                ('BTBS101', models.CharField(max_length=100)),
                ('BTBS102', models.CharField(max_length=100)),
                ('BTES103', models.CharField(max_length=100)),
                ('BTES104', models.CharField(max_length=100)),
                ('BTES105L', models.CharField(max_length=100)),
                ('BTES106', models.CharField(max_length=100)),
                ('BTBS107L', models.CharField(max_length=100)),
                ('BTES108L', models.CharField(max_length=100)),
            ],
        ),
    ]
