# Generated by Django 5.1.6 on 2025-03-30 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Candidate_Name',
            field=models.CharField(max_length=7555),
        ),
        migrations.AlterField(
            model_name='student',
            name='Roll_Number',
            field=models.CharField(max_length=7550),
        ),
    ]
